### ISSUE TITLE
Apply Official Maintainer SuperiorExtended

### ISSUE THREAD

**Issue by vherawidatama** [SuperiorExtended/manifest#1]
Hello sir, i want apply Official Maintainer for my device Realme GT Master Edition (a.k.a Lunaa) with Information on below :

---- Telegram ID : @SMGLaboratory
---- Device Tree : https://github.com/SMGLaboratory/device_realme_lunaa
---- Vendor Tree : https://github.com/SMGLaboratory/proprietary_vendor_realme_lunaa
---- Kernel Tree : https://github.com/SMGLaboratory/kernel_oneplus_sm8350
---- Common Tree : https://github.com/SMGLaboratory/device_oneplus_sm8350-common
---- Vendor Common Tree : https://github.com/SMGLaboratory/proprietary_vendor_oneplus_sm8350-common
---- Hardware Tree : https://github.com/SMGLaboratory/hardware_oplus
----  How many other roms maintan (mention them) : 1 ROMS AlphaDroid
---- any bugs : Nothing for now
----  prebuilt kernel ? if so why?, No, i'm use kernel OSS 
---- Need minimum 1 unofficial builds : done build and testing, process to publish on group

**Comment by kibria5** [comment]
> Hello sir, i want apply Official Maintainer for my device Realme GT Master Edition (a.k.a Lunaa) with Information on below :
> 
> ---- Telegram ID : @SMGLaboratory ---- Device Tree : https://github.com/SMGLaboratory/device_realme_lunaa ---- Vendor Tree : https://github.com/SMGLaboratory/proprietary_vendor_realme_lunaa ---- Kernel Tree : https://github.com/SMGLaboratory/kernel_oneplus_sm8350 ---- Common Tree : https://github.com/SMGLaboratory/device_oneplus_sm8350-common ---- Vendor Common Tree : https://github.com/SMGLaboratory/proprietary_vendor_oneplus_sm8350-common ---- Hardware Tree : https://github.com/SMGLaboratory/hardware_oplus ---- How many other roms maintan (mention them) : 1 ROMS AlphaDroid ---- any bugs : Nothing for now ---- prebuilt kernel ? if so why?, No, i'm use kernel OSS ---- Need minimum 1 unofficial builds : done build and testing, process to publish on group

we reviewed your trees, we didnt find considerable experience.
