### ISSUE TITLE
maintainer for redmi note 10 pro [SWEET]

### ISSUE THREAD

**Issue by omnitrix21** [SuperiorExtended/manifest#10]
device tree- https://github.com/omnitrix21/device_xiaomi_sweet
common tree- https://github.com/omnitrix21/device_xiaomi_sm6150-common
vendor tree- https://github.com/omnitrix21/android_vendor_xiaomi_sweet
vendor common- https://github.com/omnitrix21/android_vendor_xiaomi_sm6150-common
kernel- https://github.com/ElectroKernel/kernel_xiaomi_sweet

i will do bringup soon :)

**Comment by tejas101k** [comment]
Kindly mention your unofficial build source and also name the projects you maintain currently..
