### ISSUE TITLE
Maintainership application for Realme x3

### ISSUE THREAD

**Issue by bntxperses** [SuperiorExtended/manifest#11]
Hello! I'm applying for the official maintainership for Realme x3

---- Telegram ID: @bntxperses
---- Device Tree: https://github.com/bntxperses/device_realme_x3
---- Vendor Tree: https://github.com/bntxperses/vendor_realme_x3
---- Kernel Tree: https://github.com/bntxperses/android_kernel_realme_x3n
---- How many ROMs do I maintain: Superior OS, CherishOS Official, and Evolution x unofficial
---- Any bugs: Nothing
---- Need minimum 1 unofficial build: https://t.me/evolutionx3/33

**Comment by tejas101k** [comment]
Resources seems adequate so far! If the compiled build does fine and is well tested as mentioned we can look forward for official scenario.. 

**However some future provisions could be taken while mentioning off the commit messages. for eg.**

https://github.com/bntxperses/device_realme_x3/commit/16aeb78538689c87e32c1265e44a4d84f01664f3
https://github.com/bntxperses/device_realme_x3/commit/534b4e5919be8f31da474787d18ff64ecbbe030e

Also some proper authorships could be taken care of..
https://github.com/bntxperses/device_realme_x3/commit/f24d011cedd8b5e2ac5932b21f4a662ed3bd93a4

Approved! I hope you will take care of the points mentioned above..

**Comment by bntxperses** [comment]
I'll take care of all the issues you mention
