### ISSUE TITLE
Maintainership application for Redmi Note 10 (mojito/sunny)

### ISSUE THREAD

**Issue by DeandraAir** [SuperiorExtended/manifest#16]
---- Telegram ID = 6114659946 | https://t.me/DeanPerformer
---- Device Tree = https://github.com/DeandraAir/android_device_xiaomi_mojito
---- Vendor Tree = https://github.com/DeandraAir/android_vendor_xiaomi_mojito
---- Kernel Tree = https://github.com/DeandraAir/android_kernel_xiaomi_mojito
---- Any common tree : no using any common tree
---- How many other roms maintan (mention them) = I don't have an official build at the moment
---- any bugs = none
---- Need minimum 1 unofficial builds = https://t.me/RedmiNote10IDUpdate/1402

**Comment by Ghosuto** [comment]
You didn't even properly maintain this dt and commit history is totally messed up, all I can see 4-5 bringup for different roms 

1. Fix/clean commit
2. Give proper commit name
3. small tip - Learn git properly

Then think of applying for any official

**Comment by ashutoshchettri** [comment]
For real? 
First properly learn to use git, maintain authorship, maintain commit history then think of applying to any official roms.
