### ISSUE TITLE
Want to apply official maintainership for SuperiorOs Extended for POCO X4 PRO (veux)

### ISSUE THREAD

**Issue by MrTopia** [SuperiorExtended/manifest#18]
• Telegram ID - MrTopiA
• Device Tree - https://github.com/alexandrusemina/device_xiaomi_veux/tree/derp
• Vendor Tree - https://gitlab.com/nnippon99/vendor_xiaomi_veux
• Kernel Tree - https://github.com/nnippon99/device_xiaomi_veux-kernel
https://github.com/nnippon99/kernel_xiaomi_sm6375

• Other Roms maintained - FireDroid 1.9 Android 13
• Bug - No bugs noted in unofficial build of SuperiorOS Extended
Link- https://sourceforge.net/projects/topia-builds/files/SuperiorExtended/SuperiorOS-EXTENDED-veux-GAPPS-20231120-1403.zip/download

• No Custom Kernel used

**Comment by FPSensor** [comment]
> • Telegram ID - MrTopiA • Device Tree - https://github.com/alexandrusemina/device_xiaomi_veux/tree/derp • Vendor Tree - https://gitlab.com/nnippon99/vendor_xiaomi_veux • Kernel Tree - https://github.com/nnippon99/device_xiaomi_veux-kernel https://github.com/nnippon99/kernel_xiaomi_sm6375
> 
> • Other Roms maintained - FireDroid 1.9 Android 13 • Bug - No bugs noted in unofficial build of SuperiorOS Extended Link- https://sourceforge.net/projects/topia-builds/files/SuperiorExtended/SuperiorOS-EXTENDED-veux-GAPPS-20231120-1403.zip/download
> 
> • No Custom Kernel used

If you allow me, I recommend that you do not make too many roms, keep a few (about 3 or less) and dedicate yourself to learning and improving your trees, that will make you a respected dev, not making 20 roms
and I tell you from my own experience
Greetings and I hope you take my advice for good.
