### ISSUE TITLE
Maintainership application for Redmi Note 10 Pro / Pro Max

### ISSUE THREAD

**Issue by alpha4041** [SuperiorExtended/manifest#2]
Hello! I'm applying for the official maintainership for Redmi Note 10 Pro (sweet). 
- Telegram ID: [@alph4](https://t.me/alph4/)
- Device tree: [alpha4041/android_device_xiaomi_sweet](https://github.com/alpha4041/android_device_xiaomi_sweet)
- Common device tree: [alpha4041/android_device_xiaomi_sm6150-common](https://github.com/alpha4041/android_device_xiaomi_sm6150-common)
- Vendor tree: [alpha4041/proprietary_vendor_xiaomi_sweet](https://github.com/alpha4041/proprietary_vendor_xiaomi_sweet)
- Common vendor tree: [alpha4041/proprietary_vendor_xiaomi_sm6150-common](https://github.com/alpha4041/proprietary_vendor_xiaomi_sm6150-common)
- Kernel: [alpha4041/kernel_xiaomi_sm6150](https://github.com/alpha4041/kernel_xiaomi_sm6150)
- How many ROMs I mantain: I've built RisingOS Unofficial and I was planning to apply for official but another person took the official maintainership, now I don't maintain any ROMs officially
- Any bugs: no known bugs yet
- Unofficial build: https://www.pling.com/p/2075064/

**Comment by tejas101k** [comment]
seems fine to me..
@athizz2005
