### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by GokuSan2** [SuperiorExtended/manifest#21]
### Device you want to apply for

Redmi note 10 pro/max (sweet/sweetin)

### Device Tree Sources

https://github.com/kamleshhv/device_xiaomi_sweet

### Number of ROM's you maintain officially/unofficially, also name them

2 blaze official/alphadroid unofficial

### Any Exceptions/special concern?

No

### Telegram username

@kamleshpatidar

### GitHub username

@kamleshhv

**Comment by tejas101k** [comment]
Not upto the standards yet / No bringup..
Rejected!
