### ISSUE TITLE
Suraj7v

### ISSUE THREAD

**Issue by Suraj7v** [SuperiorExtended/manifest#23]
### Device you want to apply for

Realme 3 pro (RMX1851)

### Device Tree Sources

https://github.com/Cykeek-Labs/device_realme_RMX1851
https://github.com/Cykeek-Labs/android_vendor_RMX1851
https://github.com/Cykeek-Labs/kernel_realme_sdm710-RUI2

### Number of ROM's you maintain officially/unofficially, also name them

Derpfest unofficially Alphadroid unofficially PixelOS unofficially Superior unofficially Pixel Experience unofficially

### Any Exceptions/special concern?

No 

### Telegram username

Suraj7v 

### GitHub username

Suraj7v

**Comment by ashutoshchettri** [comment]
The trees that you provided, I dont think it belongs to you. Either push it in your github or fork it, and do some contribution of your own. Also the unofficial roms you maintain are too much.

**Comment by Suraj7v** [comment]
Okay thanks..
Actually I am maintaining unofficial roms that's why I want maintain only one or two roms that's why I want official..
I'll be pushed trees on my GitHub and applied back.
Okay
