### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by LouisG1977** [SuperiorExtended/manifest#24]
### Device you want to apply for

Poco F3 (alioth)

### Device Tree Sources

https://github.com/LouisG1977/device_xiaomi_alioth
https://github.com/LouisG1977/vendor_xiaomi_alioth
https://github.com/LouisG1977/nexus_kernel_xiaomi_sm8250

### Number of ROM's you maintain officially/unofficially, also name them

No

### Any Exceptions/special concern?

No

### Telegram username

https://t.me/LuisG1977

### GitHub username

LouisG1977

**Comment by tejas101k** [comment]
We already have a maintainer for Alioth.
