### ISSUE TITLE
Maintainership application for Redmi Note 11 Pro 4G

### ISSUE THREAD

**Issue by Raejend** [SuperiorExtended/manifest#4]
---- Telegram ID : [@RndwnZ](t.me/RndwnZ)
---- Device Tree : [RndwnZ/android_device_xiaomi_viva](https://github.com/RndwnZ/android_device_xiaomi_viva)
---- Vendor Tree : [xiaomi-mt6781-devs/android_vendor_xiaomi_viva](https://github.com/xiaomi-mt6781-devs/android_vendor_xiaomi_viva)
---- Kernel Tree : [xiaomi-mt6781-devs/android_device_xiaomi_viva-kernel](https://github.com/xiaomi-mt6781-devs/android_device_xiaomi_viva-kernel) (Prebuilts)
---- Maintained : EvolutionX(UNOFFICIAL)
---- any bugs : None
---- Superior Extended Builds : [Build](https://t.me/ZanRep/138)

**Comment by athizz2005** [comment]
from much time u are building

**Comment by Raejend** [comment]
I started building for this devices around 5 month ago

**Comment by athizz2005** [comment]
u dont use ur tree?

**Comment by tejas101k** [comment]
Still much improvement needed as from official pov.. There are just Makefile edits in order to adapt source that also with a disesteem commit history. I can see many substratum overlays or props lying not in-any-par to source which are not cared being revamped
