### ISSUE TITLE
Maintainership application for MI 11X PRO / MI 11i / REDMI K40 PRO

### ISSUE THREAD

**Issue by Uxieex** [SuperiorExtended/manifest#6]
Hello! I'm applying the official maintainership for Mi 11x Pro/ Mi 11i/ Redmi K40 Pro (haydn/haydnin).

---- Telegram ID : [@AshraySingh](https://t.me/AshraySingh)
---- Device Tree : [ashraysingh/android_device_xiaomi_haydn](https://github.com/ashraysingh/android_device_xiaomi_haydn)
---- Vendor Tree : [ashraysingh/proprietary_vendor_xiaomi_haydn](https://github.com/ashraysingh/proprietary_vendor_xiaomi_haydn)
---- Common Tree : [ashraysingh/android_device_xiaomi_sm8350-common](https://github.com/ashraysingh/android_device_xiaomi_sm8350-common)
---- Kernel Tree : [ashraysingh/android_kernel_xiaomi_sm8350](https://github.com/ashraysingh/android_kernel_xiaomi_sm8350)
---- How many ROMs I mantain : Superior OS and Derpfest OS Unofficial
---- Any bugs : Nothing
---- Need minimum 1 unofficial builds : [Mi 11X Pro/K40 Pro+/Mi 11i | Updates](https://t.me/mi11xproChannel/392)

**Comment by tejas101k** [comment]
The https://github.com/ashraysingh/android_device_xiaomi_haydn/commit/a1dfc6853f6fd8d094f063b3311e2887dab6bd19 overlay is controlled by "**R.bool.config_setColorTransformAccelerated**" means you didn't care to match it with source, which would be considered as a blind addition 

How will you define this https://github.com/ashraysingh/android_device_xiaomi_haydn/commit/55842d1e27bfe2eaca88fc3b7a809bc777112672 you have dictated proprietary.txt for updated blob list but never updated the promised blobs in your proprietary vendor.. which is nothing but unconscious picking

**Comment by Uxieex** [comment]
> The [ashraysingh/android_device_xiaomi_haydn@a1dfc68](https://github.com/ashraysingh/android_device_xiaomi_sm8350-common/commit/1d1b27523e0f7aee9f022cc41f5e180f554c9798) overlay is controlled by "**R.bool.config_setColorTransformAccelerated**" means you didn't care to match it with source, which would be considered as a blind addition

I am sorry it was my mistake that i didn't overlook the source to match and add a commit for enabling night light toggle as it was working with that commit. So now i have done a commit after matching the source : [here](https://github.com/ashraysingh/android_device_xiaomi_sm8350-common/commit/1d1b27523e0f7aee9f022cc41f5e180f554c9798)

**Comment by Uxieex** [comment]
> How will you define this [ashraysingh/android_device_xiaomi_haydn@55842d1](https://github.com/ashraysingh/android_device_xiaomi_haydn/commit/55842d1e27bfe2eaca88fc3b7a809bc777112672) you have dictated proprietary.txt for updated blob list but never updated the promised blobs in your proprietary vendor.. which is nothing but unconscious picking

I had updated the blob, but after doing so, I started experiencing camera crash issues on Chinese devices. Therefore, I performed a Git reset, but I inadvertently forgot to change the version number. See file: [here](https://github.com/ashraysingh/android_device_xiaomi_haydn/blob/superior-extended/proprietary-files.txt#L1)
