### ISSUE TITLE
Maintainership application for Mi A3 (laurel_sprout)

### ISSUE THREAD

**Issue by Musical143143** [SuperiorExtended/manifest#7]
Hii Superior Xtended lead 
I Am Rayan I wish to apply official maintaining For Mi A3
Device tree : https://gitusername@github.com/Musical143143/device_xiaomi_laurel_sprout1.git
Vendor tree: https://github.com/Musical143143/Vendor_xiaomi_laurel_sprout.git
Currently I am maintaining two Roms 
1) Cherish os (Official)
2) Rising os (unofficial)
Please review my trees Thanks

**Comment by tejas101k** [comment]
Atleast care to do a bringup before applying?
