### ISSUE TITLE
Maintainership application for Mi A3 (laurel_sprout)

### ISSUE THREAD

**Issue by Musical143143** [SuperiorExtended/manifest#9]
Hi I am Rayan 
Currently I am maintaining Cherish Os Official, Rising OS(Unofficial)
Telegram ID:@RayanWorld1

Device tree
https://gitusername@github.com/Musical143143/device_xiaomi_laurel_sprout1.git

Vendor tree
 https://github.com/Musical143143/Vendor_xiaomi_laurel_sprout.git 

Kernel tree
https://github.com/Musical143143/kernel_xiaomi_laurel_sprout.git

Build link
https://t.me/riceDroid_laurelSprout/15862

**Comment by tejas101k** [comment]
Where is the unofficial released build link?


**Incomplete Application**
